server:
  address: localhost
  port: 8080
  servlet:
   context-path: /

logging:
  config: classpath:log4j2.xml

spring:
  devtools:
   restart:
    enabled: true
    exclude: static/**,public/**
  data:
    mongodb:
      flight:
        host: localhost
        port: 27017
        database: flight
        authentication-database: flight
        username: admin
        password: password
      tips:
        host: localhost
        port: 27017
        database: train
        authentication-database: train
        username: admin
        password: password
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #JDBC连接池、监控组件Druid配置
    #配置监控的统计拦截的filters，去掉后监控界面sql将无法统计，"wall"用于防火墙
    filters: stat,wall,log4j2
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢sql记录
    connectinProperties: durid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    database: MYSQL
    #show-sql用来在控制台输出JPA自动生成的sql语句
    show-sql: true
    hibernate:
      ddl-auto: update
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

# 邮件
#对应发送服务器的smtp服务地址
#发件人邮箱地址
#mail.from.address=xxxx@qq.com
##smtp授权码
#mail.from.smtp.pwd=xxxxxx
##发件人邮箱显示昵称，可以自定义
#mail.from.nickname=xxxx
mail:
  smtp:
    service: smtp.qq.com
    prot: 587
  from:
    address: 960758921@qq.com
    smtp:
      pwd: myihkkyvtxegbahg
    nickname: 邮件接口