server:
  address: localhost
  port: 8088
  servlet:
    context-path: /

logging:
  config: classpath:log4j2.xml

spring:
  devtools:
   restart:
    enabled: true
    exclude: static/**,public/**
  data:
    mongodb:
      flight:
        host: localhost
        port: 27017
        database: flight
        authentication-database: flight
        username: admin
        password: password
      tips:
        host: localhost
        port: 27017
        database: train
        authentication-database: train
        username: admin
        password: password